title: 日本の政治
description: 衆議院・参議院の議員情報を自動更新するプロジェクト

baseurl: ""
url: "https://japan-politics.github.io"

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
  - vendor/
