title: 譌･譛ｬ縺ｮ謾ｿ豐ｻ
description: 陦・ｭｰ髯｢繝ｻ蜿りｭｰ髯｢縺ｮ隴ｰ蜩｡諠・ｱ繧定・蜍墓峩譁ｰ縺吶ｋ繝励Ο繧ｸ繧ｧ繧ｯ繝・

baseurl: ""
url: "https://japan-politics.github.io"

kramdown:
  input: GFM

defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

exclude:
  - README.md
  - vendor/
